# Generated by Django 2.1.5 on 2019-07-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=100, verbose_name='Name of candidate (in block letters)')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='Gender')),
                ('caste', models.CharField(max_length=50, verbose_name='Caste')),
                ('religion', models.CharField(max_length=50, verbose_name='Religion')),
                ('community', models.CharField(max_length=50, verbose_name='Community')),
                ('permanent_address', models.TextField(verbose_name='Permanent Address')),
                ('present_address', models.TextField(help_text='Copy and paste permanent address if they are the same.', verbose_name='Present Address')),
                ('phone_1', models.CharField(help_text="Don't use spaces in the phone number.", max_length=20, verbose_name='Phone Number 1')),
                ('phone_2', models.CharField(blank=True, help_text="Don't use spaces in the phone number.", max_length=20, null=True, verbose_name='Phone Number 2 (optional)')),
                ('email', models.EmailField(max_length=254, verbose_name='Email ID')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('concession', models.TextField(verbose_name='Nature of Eligibility for fee concession')),
                ('nationality', models.CharField(default='Indian', max_length=20, verbose_name='Nationality')),
                ('state', models.CharField(max_length=30, verbose_name='State')),
                ('district', models.CharField(max_length=50, verbose_name='District')),
                ('guardian', models.CharField(max_length=15, verbose_name='Guardian')),
                ('g_occupation', models.CharField(max_length=50, verbose_name="Guardian's Occupation")),
                ('g_address', models.TextField(verbose_name="Guardian's Address")),
                ('g_phone', models.CharField(help_text="Don't use spaces in the phone number.", max_length=20, verbose_name="Guardian's Phone Number")),
                ('g_email', models.EmailField(max_length=254, verbose_name="Guardian's Email ID")),
                ('g_relationship', models.CharField(blank=True, max_length=20, null=True, verbose_name="Guardian's relationship with the student. (If 'Other' selected)")),
                ('local_guardian_name', models.CharField(max_length=100, verbose_name='Name of Local Guardian (essential in case of students outside Thiruvananthapuram')),
                ('local_guardian_address', models.TextField(verbose_name='Address of Local Guardian')),
                ('tc_number', models.CharField(max_length=50, verbose_name='Number of TC produced')),
                ('tc_date', models.DateField(verbose_name='Date of TC produced')),
                ('tc_institution', models.CharField(max_length=150, verbose_name='Institution from where TC is issued')),
                ('exam_roll_no', models.CharField(max_length=50, verbose_name='Register number of qualifying exam')),
                ('admission_no', models.CharField(max_length=10, unique=True, verbose_name='Admission Number')),
                ('tc_taken', models.BooleanField(default=False, verbose_name='Whether TC taken from GECBH')),
                ('date_of_admission', models.DateField(auto_now_add=True, verbose_name='Date of admission')),
                ('entrance_roll_no', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True, verbose_name='KEAM Entrance Roll number')),
                ('entrance_rank', models.CharField(max_length=10, verbose_name='KEAM State Merit Rank')),
                ('reservation_rank', models.CharField(blank=True, max_length=10, null=True, verbose_name='Special category/Reservation Rank')),
                ('selection_memo_number', models.CharField(max_length=20, verbose_name='Selection Memo Number')),
                ('selection_memo_date', models.DateField(verbose_name='Selection Memo Date')),
                ('alloted_college_code', models.CharField(max_length=5, verbose_name='Alloted College Code')),
                ('alloted_course_code', models.CharField(max_length=5, verbose_name='Alloted Course Code')),
                ('alloted_branch_code', models.CharField(max_length=5, verbose_name='Alloted Branch Code')),
                ('reservation_code', models.CharField(max_length=10, verbose_name='Reservation/Special Category Code')),
            ],
        ),
    ]
