# Generated by Django 2.1.5 on 2019-07-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studreg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='guardian',
            field=models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Uncle', 'Uncle'), ('Aunt', 'Aunt'), ('Grandfather', 'Grandfather'), ('Grandmother', 'Grandmother'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Other', 'Other')], max_length=15, verbose_name='Guardian'),
        ),
        migrations.AlterField(
            model_name='student',
            name='local_guardian_name',
            field=models.CharField(max_length=100, verbose_name='Name of Local Guardian (essential in case of students outside Thiruvananthapuram)'),
        ),
    ]
