# Generated by Django 2.1.5 on 2019-07-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studreg', '0002_auto_20190704_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_admission',
            field=models.DateField(auto_now_add=True, verbose_name='Date of admission (Format: 2019-01-04)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date of Birth (Format: 2002-01-04)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='selection_memo_date',
            field=models.DateField(verbose_name='Selection Memo Date (Format: 2019-01-04)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='tc_date',
            field=models.DateField(verbose_name='Date of TC produced (Format: 2019-01-04)'),
        ),
    ]
