# Generated by Django 2.1.5 on 2019-07-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studreg', '0003_auto_20190704_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_no',
            field=models.CharField(max_length=10, verbose_name='Admission Number'),
        ),
    ]
