# Generated by Django 2.1.5 on 2019-07-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studreg', '0005_auto_20190705_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='alloted_branch_code',
            field=models.CharField(max_length=10, verbose_name='Alloted Branch Code'),
        ),
        migrations.AlterField(
            model_name='student',
            name='alloted_college_code',
            field=models.CharField(max_length=10, verbose_name='Alloted College Code'),
        ),
        migrations.AlterField(
            model_name='student',
            name='alloted_course_code',
            field=models.CharField(max_length=10, verbose_name='Alloted Course Code'),
        ),
        migrations.AlterField(
            model_name='student',
            name='caste',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Caste'),
        ),
        migrations.AlterField(
            model_name='student',
            name='community',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Community'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_admission',
            field=models.DateField(auto_now_add=True, help_text='Enter date exactly as shown above.', verbose_name='Date of admission (Format: YYYY-MM-DD)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(help_text='Enter date exactly as shown above.', verbose_name='Date of Birth (Format: YYYY-MM-DD)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='entrance_roll_no',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='KEAM Entrance Roll number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='g_name',
            field=models.CharField(max_length=100, verbose_name="Guardian's name"),
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Religion'),
        ),
        migrations.AlterField(
            model_name='student',
            name='selection_memo_date',
            field=models.DateField(help_text='Enter date exactly as shown above.', verbose_name='Selection Memo Date (Format: YYYY-MM-DD)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='tc_date',
            field=models.DateField(help_text='Enter date exactly as shown above.', verbose_name='Date of TC produced (Format: YYYY-MM-DD)'),
        ),
    ]
