# Generated by Django 2.1.5 on 2019-07-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studreg', '0006_auto_20190706_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='amount',
            field=models.CharField(default=0, max_length=20, verbose_name='Amount (Rs)'),
        ),
        migrations.AddField(
            model_name='student',
            name='bank_receipt_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bank Receipt No.'),
        ),
        migrations.AddField(
            model_name='student',
            name='community_submitted',
            field=models.BooleanField(default=False, verbose_name='Community Certificate'),
        ),
        migrations.AddField(
            model_name='student',
            name='fee_concession',
            field=models.BooleanField(default=False, help_text='Tick if eligible.', verbose_name='Fee Concession'),
        ),
        migrations.AddField(
            model_name='student',
            name='marklist_submitted',
            field=models.BooleanField(default=False, verbose_name='Marklist'),
        ),
        migrations.AddField(
            model_name='student',
            name='migration_submitted',
            field=models.BooleanField(default=False, verbose_name='Migration Certificate (ICSE/CBSE/Diploma)'),
        ),
        migrations.AddField(
            model_name='student',
            name='tc_submitted',
            field=models.BooleanField(default=False, verbose_name='Transfer Certificate'),
        ),
        migrations.AlterField(
            model_name='student',
            name='alloted_branch_code',
            field=models.CharField(choices=[('CE', 'CE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('IT', 'IT'), ('ME', 'ME')], max_length=10, verbose_name='Alloted Branch Code'),
        ),
        migrations.AlterField(
            model_name='student',
            name='alloted_college_code',
            field=models.CharField(default='TRV', max_length=10, verbose_name='Alloted College Code'),
        ),
        migrations.AlterField(
            model_name='student',
            name='alloted_course_code',
            field=models.CharField(choices=[('BTech', 'BTech'), ('MTech', 'MTech'), ('PhD', 'PhD')], max_length=10, verbose_name='Alloted Course Code'),
        ),
        migrations.AlterField(
            model_name='student',
            name='concession',
            field=models.CharField(choices=[('No eligibility', 'No eligibility'), ('SC', 'SC'), ('ST', 'ST'), ('OEC', 'OEC')], default='No eligibility', max_length=20, verbose_name='Nature of Eligibility for fee concession'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='state',
            field=models.CharField(default='Kerala', max_length=30, verbose_name='State'),
        ),
    ]
