# Generated by Django 2.1.5 on 2019-07-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studreg', '0008_auto_20190707_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='present_address',
            field=models.TextField(verbose_name='Present Address'),
        ),
    ]
