# Generated by Django 2.1.5 on 2019-07-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studreg', '0009_auto_20190707_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='state',
            field=models.CharField(default='Kerala', max_length=50, verbose_name='State'),
        ),
    ]
