# Generated by Django 2.1.5 on 2019-07-08 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studreg', '0011_student_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='timestamp',
            new_name='time_stamp',
        ),
    ]
