# Generated by Django 2.1.5 on 2019-07-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studreg', '0012_auto_20190708_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='district',
            field=models.CharField(max_length=100, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='student',
            name='g_phone',
            field=models.CharField(help_text="Don't use spaces in the phone number.", max_length=25, verbose_name="Guardian's Phone Number"),
        ),
        migrations.AlterField(
            model_name='student',
            name='g_relationship',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Guardian's relationship with the student. (If 'Other' selected)"),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_1',
            field=models.CharField(help_text="Don't use spaces in the phone number.", max_length=25, verbose_name='Phone Number 1'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_2',
            field=models.CharField(blank=True, help_text="Don't use spaces in the phone number.", max_length=25, null=True, verbose_name='Phone Number 2 (optional)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='state',
            field=models.CharField(default='Kerala', max_length=100, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='student',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Timestamp'),
        ),
    ]
